<?php

class Dashboard extends AE_Controller{

	public function index(){

		$dados['titulo'] = 'ACES English';
		$dados['subview'] = 'app/dashboard/body';

		$this->load->view('app/interface/interface', $dados);

	}


	public function __controller() {
		parent ::__controller(); // TODO: Change the autogenerated stub
	}
}
