<?php

class LikeOrDislike extends AE_Controller {

	public function index(){}

	public function save(){
		$type = $this->input->get('likeOrDislike');
		$postId = $this->input->get('postId');
		$personId = $this->auth->get_user_data('Id');
		$result = $this->ldmodel->save($personId, $type, $postId);
	}

	public function delete(){
		$type = $this->input->get('likeOrDislike');
		$postId = $this->input->get('postId');
		$personId = $this->auth->get_user_data('Id');
		$result = $this->ldmodel->delete($personId, $type, $postId);
	}

	public function __construct() {
		parent ::__construct(); // TODO: Change the autogenerated stub

		$this->load->model('Likeordislike_model', 'ldmodel');
	}
}
