<?php

class LikeOrDislike extends AE_Controller {

	public function index(){}

	public function save(){
		$postId = $this->input->get('postId');
		$personId = $this->auth->GetUserData('UserId');
		$result = $this->ldmodel->save($personId, $postId);

        if($result->TotalLikes > 0):
            $this->rest->Code(200)->Result($result)->Message("Like registrado com sucesso.")->Run();
        else:
            $this->rest->Code(500)->Result($result)->Message("Houve um erro ao cadastrar o like.")->Run();
        endif;
	}

	public function __construct() {
		parent ::__construct(); // TODO: Change the autogenerated stub

		$this->load->model('Likeordislike_model', 'ldmodel');
	}
}
